### ISSUE TITLE
Unable to install analytics-node

### ISSUE THREAD

**Issue by abhinavchawla** [segmentio/analytics-node#250] opened 2020-08-08 18:16 UTC
Receiving this error while installing analytics-node
```
npm install -g analytics-node
npm ERR! code ETARGET
npm ERR! notarget No matching version found for axios-retry@^3.0.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'analytics-node'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abchawla/.npm/_logs/2020-08-08T18_13_05_110Z-debug.log
```

What would be the fix for this?

**Comment by pbassut** [comment] 2021-01-11 05:42
That's really strange. But I'm certain that only happens in your env. Maybe your .npmrc is messed up? Like it's hitting something else other than npmjs.com?
Cause we're definitely there: https://www.npmjs.com/package/analytics-node

**Comment by pbassut** [comment] 2021-02-03 05:13
Sorry. Re-reading this now I see the issue is with axios-retry not being found. 
Now, why you're using `-g` to install it globally? Shoudn't that be dropped?

**Comment by pbassut** [comment] 2021-03-10 03:30
Since we haven't got any responses here and it's likely a npm usage issue. We'll close this. Please re-open if you find necessary.

**Closed** 2021-03-10 18:15 UTC
