### ISSUE TITLE
Typescript import doesn't work.

### ISSUE THREAD

**Issue by ashok-sc** [segmentio/analytics-node#132] opened 2017-11-04 00:10 UTC
When importing Analytics using Typescript:
`import Analytics from 'analytics-node';`

I get the following error:

`node_modules/@types/analytics-node/index"' has no default export.`

I can revert to this `const Analytics = require('analytics-node');`, but I should be able to do this with Typescript imports right? 

As you can see above, I do have the type definitions installed as well.

**Comment by f2prateek** [comment] 2017-11-04 00:18
I'm not that familiar with typescript, but looking at https://github.com/Microsoft/TypeScript/issues/3337#issuecomment-107971371; did you try this?

```
import * as analytics from 'analytics-node';
```

**Comment by ashok-sc** [comment] 2017-11-04 02:43
When I use that type of import I get the following error:
`resolves to a non-module entity and cannot be imported using this construct.`

Removing the type definitions completely fixes this problem. This is unfortunate :(.

**Comment by stephenmathieson** [comment] 2017-11-04 17:49
I'm not too sure how TypeScript works, but how is it expecting us to export the Analytics class?

I think this may be an issue with `@types/analytics-node` btw.

**Comment by lev-kuznetsov** [comment] 2017-11-07 20:36
Looking at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/analytics-node/index.d.ts I think you're supposed to import like this:

```
import {Analytics} from 'analytics-node'
```

**Comment by f2prateek** [comment] 2017-11-23 01:00
hey @ashok-sc , could you try @lev-kuznetsov 's suggestion? Closing this issue for now, but please re-open if it's still an issue.

**Closed by f2prateek** 2017-11-23 01:00 UTC

**Comment by havenchyk** [comment] 2018-02-12 07:39
@f2prateek it's definitely not working and issue need to be reopened

**Comment by JQuezada0** [comment] 2018-02-13 20:09
This should be reopened. This is still an issue.

**Comment by f2prateek** [comment] 2018-02-13 21:19
I don't think this is the right place for the issue- the issue is from wherever your analytics-node types are being defined, which is outside of this repostiroty, e.g. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/analytics-node/index.d.ts. You should open this issue for whichever library is the one you're using to package the TypeScript information.

**Comment by ajsharp** [comment] 2018-04-09 23:03
@f2prateek Some packages declare their own types inside the home repo. +1 for doing that here

**Comment by f2prateek** [comment] 2018-04-10 05:11
@ajsharp seems reasonable - I closed the issue because the original post was reporting a bug in a different package. Feel free to open a new issue if you'd like to request TypeScript support natively in this package. I'm not sure if we'll add it soon, but it would serve as a good forum for people to track the issue and show their interest.

**Comment by stephenmathieson** [comment] 2018-04-10 15:14
IMO, since Segment doesn't use TypeScript here, the definitions don't really belong here either. Putting them in this repository is just putting additional maintenance on the Segment team that isn't completely necessary, since the @definitelytyped org exists.

**Comment by RXminuS** [comment] 2018-07-03 10:30
BTW, this is the solution https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23760

**Comment by stephenmathieson** [comment] 2018-07-03 13:21
> It's like saying that the Docs should live in a different repo because you only ever look at the code internally anyways. 

It's nothing like that. TypeScript is not JavaScript, so the JavaScript developers that maintain this project are going to do a bad job at maintaining the TS definitions. Just because *you* decided to learn TypeScript does not mean Segment's JS devs have. When I was still there, there were literally no TypeScript projects in the entire `segmentio` org (1000s of repos). We didn't use TS at all, so we'd do a horrible job of maintaining definitions for it. This is exactly why the DefinitelyTyped organization exists.

**Comment by havenchyk** [comment] 2018-07-04 11:56
@RXminuS so, does it mean that solution is to use `esModuleInterop` flag?
